### ISSUE TITLE
kit reset limit not working

### ISSUE THREAD

**Issue by tealtoxic** [trentech/EasyKits-for-Bukkit#10]
hi, awesme plugin :)

i give myself easykit.* perm.

make kit named 'mula' 

restart server.

login my test account 'onidipp', use mula (limit 1 time), works great! leave test acc afk.

login admin acc, use /kit reset limit mula onidipp, system return limit does not exist in red text. helep.

**Comment by trentech** [comment]
Resolved. Release pending approval on bukkit

a420a3cbf1b1a1e41e079c51fbfcb887f851b196

**Comment by tealtoxic** [comment]
thank you

**Comment by trentech** [comment]
I posted a release here too if you don't want to wait. I always forget to do that.

https://github.com/trentech/EasyKits-for-Bukkit/releases

**Comment by tealtoxic** [comment]
:D alright! thank you
