### ISSUE TITLE
Price and Cooldown not Working

### ISSUE THREAD

**Issue by ryanchba** [trentech/EasyKits-for-Bukkit#4]
Setting the price and cooldown of a kit is not working currently. I can run the command to change them both and the console says it updates, but the price and cooldown are not actually changing. Please help.

**Comment by trentech** [comment]
Sorry, bukkit devs have to approve the update. They're usually pretty quick about it

**Comment by trentech** [comment]
Here I've posted a release on this page
https://github.com/trentech/EasyKits-for-Bukkit/releases

**Comment by ryanchba** [comment]
Great!! The price is fixed! The cooldowns are still not, though for some reason. I'm not sure why. 
Also, another weird thing I've noticed is the permission easykits.kit.<kitname> is required for the player to be able to use the kit, and easykits.kits.<kitname> is required for the player to see the kit in /kit list. I'm not sure if this was on purpose or not. I'm fine with it! Just wanted to let you know.

**Comment by trentech** [comment]
OK further investigating I have found a couple bugs. One that broke cooldown and limits, and a permission bug where one location is looking for easykits.kits.* and another that's using easykits.kit.* It should be kits not kit as shown in the documentation on the bukkit page. I'm testing some changes now and will roll out an update once I've confirmed the issues are resolved.

**Comment by ryanchba** [comment]
Thank you! You're actually the most responsive person I've ever had on these pages, and I really appreciate it. You might want to look into signs as well, as those weren't working for me either, but that could have been user error or something else on my end, and I'm not too upset about it. For your info, the signs would format properly, but clicking on them would do nothing.

**Comment by trentech** [comment]
I'm usually not this responsive, you just caught me at the right time :P. I'll take a look at the sign issue. I think someone on the bukkit page also complained they were not working as well

**Comment by ryanchba** [comment]
Alrighty! Well I'll be here haha, so let me know if there's anything I can do to help (I know there probably isn't, but I'd rather offer than not offer!), or if you're able to fix it. Thanks again

**Comment by trentech** [comment]
Fixed. For real this time! Signs too. Thanks for the feedback. Let me know if any other problems arise, I'll do my best to fix them as quick as I can
