### ISSUE TITLE
/kit give <kitname> <playername> not working

### ISSUE THREAD

**Issue by ryanchba** [trentech/EasyKits-for-Bukkit#5]
Hi! I'm trying to use the command "/kit give" from the console, but its spitting out some errors at me, and I was hoping you could take a look. Thanks!
![Error](https://user-images.githubusercontent.com/68577700/102122777-9b89e500-3e0b-11eb-9e65-ffd63a4e3b70.JPG)

**Comment by trentech** [comment]
Resolved. Update pending approval on bukkit page

a154c3ab8c8bb7fe9ee469dc768a031c23deb0a1
